ekf_filter_node:
  ros__parameters:
    #Robots gets new estimate every 15 seconds.
    frequency: 15.0
    #We tell to filter to focus on x and y position and yaw angle, ignoring z, roll and pitch.
    two_d_mode: true
    #publish to the tf topic
    publish_tf: true
    #global reference frame 
    map_frame: map  
    #Tracks robot movemment 
    odom_frame: odom
    #Robot's body frame
    base_link_frame: base_footprint
    #parent for Tf published by the filter
    world_frame: odom 
    #Wheel odometry is our main source of information about the robot's movement, so we set it as the primary input.
    odom0:mecanum_drive_controller/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]

    #We also have an IMU that gives us information about the robot's orientation and angular velocity, so we set it as a secondary input.
    imu0: imu/data
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,
                  true, true, true,
                  false, false, false]

  